transaction support for redis distributed
redis/redis-rb pull request #941
Opened 2020-09-04 19:33 UTC by EiNSTeiN-

I am trying to use `watch` and `multi` with `Redis::Distributed`. My code looks like this:

```ruby
r.watch("{uuid}:data", "{uuid}:version") do
  current = r.get("{uuid}:version")
  r.multi do
    r.set("{uuid}:data", new_data)
    r.set("{uuid}:version", current + 1)
  end
end
```

Given all keys can be tagged, they will all end up on the same node, so this should work with `Redis::Distributed` without issue. An additional assumption is that the caller will use the block syntax for `watch` which is thread safe, or will handle thread safety in another way outside of `Redis::Distributed`.

I implemented that by keeping a copy of the key tag or the key if the key itself isn't tagged, and ensure that all commands are issued with the same key or key tag until one of these things happen:
1) `exec`, `unwatch` or `discard` is explicitly called
2) `exec` is implicitly called at the end of the `multi` block
3) `unwatch` is implicitly called when a `StandardError` is raised within a `watch` block

2020-09-05 00:44 UTC, supercaracal commented
CI tests of the repository tend to be flaky now. These irrelevant failures are ignorable. They will be resolved by #930.

2020-09-07 11:30 UTC, byroot requested changes

2020-09-07 11:30 UTC, byroot commented on lib/redis/distributed.rb
> +          @watch_key = nil
That's not good enough, you want to reset `@watch_key` from an `ensure` block. Here you only reset it on error.

2020-09-07 11:32 UTC, byroot commented on lib/redis/distributed.rb
> +          @watch_key = nil
Hum, actually scratch that, it seems `watch do` is not expected to unwatch... that's a very weird behavior :/

2020-09-07 14:33 UTC, byroot approved these changes
Ok, so ignore my previous comment. I wasn't so familiar with the watch interface. Turns out the unwatch has to be manual, sounds like a terrible API to me but hey...

2020-09-07 14:34 UTC, merged